=== adamb924/mortal-engine/schemata/stems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:me="https://www.adambaker.org/mortal-engine.php"
targetNamespace="https://www.adambaker.org/mortal-engine.php">


    <!-- Definition for a writing system -->
    <xs:element name="stems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="stem" type="me:stem" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="stem">
        <xs:choice>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="form" type="me:form" minOccurs="1"/>
                <xs:element name="tag" type="xs:string"/>
            </xs:choice>
            <xs:element name="allomorph" type="me:allomorph" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
    
    <!-- form -->
    <xs:complexType name="allomorph">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="form" type="me:form" minOccurs="1"/>
            <xs:element name="tag" type="xs:string"/>
        </xs:choice>
    </xs:complexType>

    <!-- form -->
    <xs:complexType name="form">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== adamb924/mortal-engine/examples/12-stems.xml
<?xml version="1.0" encoding="UTF-8"?>
<stems
    xmlns="https://www.adambaker.org/mortal-engine/stems"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.adambaker.org/mortal-engine/stems stems.xsd">
    <stem>
        <form lang="wk-LA">sit</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">sɪn</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">ben</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kɛm</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">mot</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kɔŋ</form>
        <tag>noun</tag>
    </stem>
    <!-- <stem>
        <form lang="wk-LA">göl</form>
        <tag>verb</tag>
    </stem> -->
    <stem>
        <form lang="wk-LA">sep</form>
        <tag>verb</tag>
    </stem>
    <stem>
        <form lang="wk-LA">pop</form>
        <tag>verb</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kim</form>
        <tag>verb</tag>
    </stem>
</stems>

=== adamb924/mortal-engine/examples/26-stems.xml
<?xml version="1.0" encoding="UTF-8"?>
<stems xmlns="https://www.adambaker.org/mortal-engine/stems"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../schemata stems.xsd">
    <stem>
        <form lang="wk-LA">don</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <allomorph portmanteau="[Stem][Dative]">
            <form lang="wk-LA">shunga</form>
            <tag>noun</tag>
        </allomorph>
        <allomorph>
            <form lang="wk-LA">shu</form>
            <tag>noun</tag>
        </allomorph>
    </stem>
</stems>

=== adamb924/mortal-engine/examples/25-stems.xml
<?xml version="1.0" encoding="UTF-8"?>
<stems
    xmlns="https://www.adambaker.org/mortal-engine/stems"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.adambaker.org/mortal-engine/stems stems.xsd">
    <stem>
        <form lang="wk-LA">sit</form>
        <form lang="wk-AR">سیت</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">sɪn</form>
        <form lang="wk-AR">سین</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">ben</form>
        <form lang="wk-AR">بن</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kɛm</form>
        <form lang="wk-AR">کم</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">mot</form>
        <form lang="wk-AR">موت</form>
        <tag>noun</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kɔŋ</form>
        <form lang="wk-AR">کون</form>
        <tag>noun</tag>
    </stem>
    <!-- <stem>
        <form lang="wk-LA">göl</form>
        <tag>verb</tag>
    </stem> -->
    <stem>
        <form lang="wk-LA">sep</form>
        <form lang="wk-AR">سپ</form>
        <tag>verb</tag>
    </stem>
    <stem>
        <form lang="wk-LA">pop</form>
        <form lang="wk-AR">پوپ</form>
        <tag>verb</tag>
    </stem>
    <stem>
        <form lang="wk-LA">kim</form>
        <form lang="wk-AR">کیم</form>
        <tag>verb</tag>
    </stem>
</stems>

=== adamb924/mortal-engine/examples/01-stems.xml
<?xml version="1.0" encoding="UTF-8"?>
<stems
    xmlns="https://www.adambaker.org/mortal-engine/stems"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.adambaker.org/mortal-engine/stems stems.xsd">
    <stem>
        <form lang="wk-AR">بیل</form>
        <form lang="wk-LA">bil</form>
        <tag>verb</tag>
        <tag>front</tag>
    </stem>
    <stem>
        <form lang="wk-AR">گؤر‍</form>
        <form lang="wk-LA">göl</form>
        <tag>verb</tag>
        <tag>front</tag>
    </stem>
    <stem>
        <form lang="wk-AR">سال</form>
        <form lang="wk-LA">sal</form>
        <tag>verb</tag>
        <tag>back</tag>
    </stem>
    <stem>
        <form lang="wk-AR">سال</form>
        <form lang="wk-LA">sal</form>
        <tag>noun</tag>
        <tag>back</tag>
    </stem>
    <stem>
        <form lang="wk-AR">آی</form>
        <form lang="wk-LA">aý</form>
        <tag>noun</tag>
        <tag>back</tag>
    </stem>
    <stem>
        <form lang="wk-AR">آتا</form>
        <form lang="wk-LA">ata</form>
        <tag>noun</tag>
        <tag>back</tag>
    </stem>
    <stem>
        <form lang="wk-AR">دوْن</form>
        <form lang="wk-LA">don</form>
        <tag>noun</tag>
        <tag>back</tag>
    </stem>
    <stem>
        <form lang="wk-AR">گؤر</form>
        <form lang="wk-LA">gör</form>
        <tag>verb</tag>
        <tag>front</tag>
    </stem>
    <stem>
        <form lang="wk-AR">کؤیناک</form>
        <form lang="wk-LA">köýnek</form>
        <tag>noun</tag>
        <tag>front</tag>
    </stem>
    <stem>
        <form lang="wk-AR">گؤز</form>
        <form lang="wk-LA">göz</form>
        <tag>noun</tag>
        <tag>front</tag>
    </stem>
</stems>
