=== adamb924/mortal-engine/schemata/tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:met="https://www.adambaker.org/mortal-engine/tests"
targetNamespace="https://www.adambaker.org/mortal-engine/tests">

    <xs:element name="tests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sqlite-database" type="met:database" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="schema" type="met:schema"/>
                    </xs:choice>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
    
    <xs:complexType name="schema" mixed="true">
        <xs:sequence>
            <xs:element name="morphology-file" type="xs:string"/>
            <xs:choice>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="transduction-test" type="met:transduction-test"/>
                    <xs:element name="parsing-test" type="met:parsing-test"/>
                    <xs:element name="recognition-test" type="met:recognition-test"/>
                    <xs:element name="suggestion-test" type="met:suggestion-test"/>
                    <xs:element name="interlinear-gloss-test" type="met:interlinear-gloss-test"/>
                    <xs:element name="stem-replacement-test" type="met:stem-replacement-test"/>
                    <xs:element name="accept" type="met:acceptance-test"/>
                    <xs:element name="reject" type="met:acceptance-test"/>
                    <xs:element name="generation-test" type="met:generation-test"/>
                    <xs:element name="generate" type="met:quick-generation-test"/>
                    <xs:element name="blank" type="xs:string" fixed=""/>
                    <xs:element name="message" type="xs:string"/>
                </xs:choice>
            </xs:choice>    
        </xs:sequence>
        <xs:attribute name="sound-and-fury" type="xs:string"/>
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="show-model" type="met:true-false-type" use="optional" default="true"/>
    </xs:complexType>

    <xs:complexType name="test">
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
        <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
    </xs:complexType>

    <xs:complexType name="transduction-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="interlinear-gloss-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="parsing-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="suggestion-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:stem-label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="recognition-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="should-be-accepted" type="met:yes-no-type"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="acceptance-test">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
                <xs:attribute name="label" type="xs:string" use="optional"/>
                <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
                <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="stem-replacement-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="replacement-stem" type="met:stem"/>
                    <xs:element name="output" type="met:form"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="quick-generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:attribute name="morphemes" type="xs:string"/>
                <xs:attribute name="stem" type="xs:unsignedLong"/>
                <xs:attribute name="lang" type="xs:string"/>
                <xs:attribute name="output" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="morphemes" type="xs:string"/>
                    <xs:element name="stem">
                        <xs:complexType>
                            <xs:attribute name="id" type="xs:unsignedLong" use="required"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:attribute name="filename" type="xs:string"/>
        <xs:attribute name="database-name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem-label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="stem" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem">
        <xs:sequence>
            <xs:element name="form" type="met:form" maxOccurs="unbounded"/>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="form">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="true-false-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yes-no-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== adamb924/mortal-engine/examples/20-Create-Allomorphs-6.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 6">
    <morphology-file>20-Create-Allomorphs-6.xml</morphology-file>
    <message>Identical behavior to 19-Create-Allomorphs-5.xml</message>
    <reject lang="wk-LA">sit</reject>
    <reject lang="wk-LA">ben</reject>
    <accept lang="wk-LA">site</accept>
    <accept lang="wk-LA">sitana</accept>
    <message>But labials are prenasalized:</message>
    <reject lang="wk-LA">bene</reject>
    <accept lang="wk-LA">ᵐbene</accept>
    <reject lang="wk-LA">benana</reject>
    <accept lang="wk-LA">ᵐbenana</accept>
    <message>But identical behavior for verbs as well:</message>
    <reject lang="wk-LA">sep</reject>
    <reject lang="wk-LA">pop</reject>
    <accept lang="wk-LA">sepe</accept>
    <accept lang="wk-LA">pope</accept>
    <accept lang="wk-LA">sepono</accept>
    <accept lang="wk-LA">popono</accept>
</schema>

=== adamb924/mortal-engine/examples/test-gallery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <tests> is the root element -->
<tests
    xmlns="https://www.adambaker.org/mortal-engine/tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests tests.xsd">

    <!-- The <tests> element contains one or more <schema> elements. 
         There is no requirement to use more than one schema. It just
         provides a more organized output if you want that. -->
    <schema label="Just a single schema in this example">

        <!-- The <morphology-file> should be a path to a morphology file.
            This is the morphology that Mortal Engine will use for these tests. -->
        <morphology-file>03-Optional-Affixes.xml</morphology-file>

        <!-- A recognition test is simply whether a form should be 
            accepted by the model or not. -->
        <recognition-test label="Acceptance of a correctly affixed form">
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>

        <recognition-test label="Acceptance of a correctly affixed form">
            <input lang="wk-LA">this-is-not-a-good-input</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>

        <!-- The following two shorthands are equivalent to the two previous tests -->
        <accept lang="wk-LA">atalar</accept>
        <reject lang="wk-LA">this-is-not-a-good-input</reject>

        <!-- A parsing test checks whether the model produces correct
            morphological analyses of your input. The <label> elements
            contain the labels of morphemes, which are specified in your
            model. You can include multiple <output> tags if that is correct
            for your model (i.e., amgbiguous inputs). The test will fail if
            the list of parsings from the model is not identical to the list
            you provide here. (The order of the output is irrelevant, though.)  -->
        <parsing-test label="Check that the correct morphemes are selected">
            <input lang="wk-LA">atalar</input>
            <output>
                <label>Stem</label>
                <label>Plural</label>
            </output>
        </parsing-test>

        <!-- A transduction test is similar to a parsing test. You can have
            multiple <output> tags. The test fails if the transductions
            generated by the model are not identical to those you list. -->
        <transduction-test label="Changing writing systems">
            <input lang="wk-LA">atalar</input>
            <output lang="wk-AR">آتالار</output>
        </transduction-test>

        <!-- The suggestion test suggests different possible parsings for
            a given input. (In this case, “unknown” is not a word in the
            language.) -->
        <suggestion-test label="Suggest possible stems">
            <input lang="wk-LA">unknownlar</input>
            <output>
                <stem>Stem</stem>
            </output>
            <output>
                <stem>Stem</stem>
                <label>Plural</label>
            </output>
        </suggestion-test>
    </schema>
</tests>

=== adamb924/mortal-engine/examples/07-Forks.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Forks">
    <morphology-file>07-Forks.xml</morphology-file>
    <accept lang="wk-LA">bil_PRESENT_present.1s</accept>
    <accept lang="wk-LA">bil_PRESENT_present.2s</accept>
    <reject lang="wk-LA">bil_FUTURE_present.1s</reject>
    <reject lang="wk-LA">bil_FUTURE_present.2s</reject>
    <reject lang="wk-LA">bil_PRESENT_future.1s</reject>
    <reject lang="wk-LA">bil_PRESENT_future.2s</reject>
    <accept lang="wk-LA">bil_FUTURE_future.1s</accept>
    <accept lang="wk-LA">bil_FUTURE_future.2s</accept>
</schema>

=== adamb924/mortal-engine/examples/19-Create-Allomorphs-5.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 5">
    <morphology-file>19-Create-Allomorphs-5.xml</morphology-file>
    <message>Identical behavior to 17-Create-Allomorphs-4.xml</message>
    <reject lang="wk-LA">sit</reject>
    <reject lang="wk-LA">ben</reject>
    <accept lang="wk-LA">site</accept>
    <accept lang="wk-LA">bene</accept>
    <accept lang="wk-LA">sitana</accept>
    <accept lang="wk-LA">benana</accept>
    <message>Analogous behavior for verbs as well:</message>
    <reject lang="wk-LA">sep</reject>
    <reject lang="wk-LA">pop</reject>
    <accept lang="wk-LA">sepe</accept>
    <accept lang="wk-LA">pope</accept>
    <accept lang="wk-LA">sepono</accept>
    <accept lang="wk-LA">popono</accept>
</schema>

=== adamb924/mortal-engine/examples/10-Jumps.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Jumps">
    <morphology-file>10-Jumps.xml</morphology-file>
    <message>Case suffixes can go on nouns</message>
    <accept lang="wk-LA">don</accept>
    <accept lang="wk-LA">donCase</accept>
    <message>Case suffixes don't go on verbs</message>
    <reject lang="wk-LA">bilCase</reject>
    <message>Infinitive suffixation, with subsequent case affixation</message>
    <accept lang="wk-LA">bilinf</accept>
    <accept lang="wk-LA">bilinfCase</accept>
    <message>(Obviously) Infinitive suffixes don't go on nouns</message>
    <reject lang="wk-LA">doninf</reject>
</schema>

=== adamb924/mortal-engine/examples/14-Create-Allomorphs.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs">
    <morphology-file>14-Create-Allomorphs.xml</morphology-file>
    <message>Success means identical output to 13-Shared-Conditions.xml</message>
    <reject lang="wk-LA">sɪn</reject>
    <accept lang="wk-LA">esit</accept>
    <accept lang="wk-LA">eben</accept>
    <accept lang="wk-LA">emot</accept>
    <reject lang="wk-LA">ɛsit</reject>
    <reject lang="wk-LA">ɛben</reject>
    <reject lang="wk-LA">ɛmot</reject>
    <accept lang="wk-LA">ɛsɪn</accept>
    <accept lang="wk-LA">ɛkɛm</accept>
    <accept lang="wk-LA">ɛkɔŋ</accept>
    <reject lang="wk-LA">esɪn</reject>
    <reject lang="wk-LA">ekɛm</reject>
    <reject lang="wk-LA">ekɔŋ</reject>
    <accept lang="wk-LA">enosit</accept>
    <accept lang="wk-LA">enoben</accept>
    <accept lang="wk-LA">enomot</accept>
    <reject lang="wk-LA">ɛnɔsit</reject>
    <reject lang="wk-LA">ɛnɔben</reject>
    <reject lang="wk-LA">ɛnɔmot</reject>
    <accept lang="wk-LA">ɛnɔsɪn</accept>
    <accept lang="wk-LA">ɛnɔkɛm</accept>
    <accept lang="wk-LA">ɛnɔkɔŋ</accept>
    <reject lang="wk-LA">enosɪn</reject>
    <reject lang="wk-LA">enokɛm</reject>
    <reject lang="wk-LA">enokɔŋ</reject>
</schema>

=== adamb924/mortal-engine/examples/11-Jumps-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Jumps 2">
    <morphology-file>11-Jumps-2.xml</morphology-file>
    <message>Case suffixes go on nouns</message>
    <accept lang="wk-LA">don</accept>
    <accept lang="wk-LA">donCase</accept>
    <message>Case suffixes don't go on verbs</message>
    <reject lang="wk-LA">bilCase</reject>
    <message>Infinitive suffixation, without a case suffix, is no longer possible</message>
    <reject lang="wk-LA">bilinf</reject>
    <message>Infinitive suffixation, with subsequent case affixation</message>
    <accept lang="wk-LA">bilinfCase</accept>
    <message>(Obviously) Infinitive suffixes don't go on nouns</message>
    <reject lang="wk-LA">doninf</reject>
</schema>

=== adamb924/mortal-engine/examples/06-Mutually-Exclusive-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Mutually Exclusive Morphemes Example 2">
    <morphology-file>06-Mutually-Exclusive-2.xml</morphology-file>
    <accept lang="wk-LA">ata</accept>
    <accept lang="wk-LA">atalar</accept>
    <accept lang="wk-LA">atalary</accept>
    <accept lang="wk-LA">atalarym</accept>
    <reject lang="wk-LA">atalarymy</reject>
    <accept lang="wk-LA">göz</accept>
    <accept lang="wk-LA">gözler</accept>
    <accept lang="wk-LA">gözleri</accept>
    <accept lang="wk-LA">gözlerim</accept>
    <reject lang="wk-LA">gözlarim</reject>
    <reject lang="wk-LA">gözlerym</reject>
    <reject lang="wk-LA">gözlerimi</reject>
</schema>
