=== adamb924/mortal-engine/schemata/tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:met="https://www.adambaker.org/mortal-engine/tests"
targetNamespace="https://www.adambaker.org/mortal-engine/tests">

    <xs:element name="tests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sqlite-database" type="met:database" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="schema" type="met:schema"/>
                    </xs:choice>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
    
    <xs:complexType name="schema" mixed="true">
        <xs:sequence>
            <xs:element name="morphology-file" type="xs:string"/>
            <xs:choice>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="transduction-test" type="met:transduction-test"/>
                    <xs:element name="parsing-test" type="met:parsing-test"/>
                    <xs:element name="recognition-test" type="met:recognition-test"/>
                    <xs:element name="suggestion-test" type="met:suggestion-test"/>
                    <xs:element name="interlinear-gloss-test" type="met:interlinear-gloss-test"/>
                    <xs:element name="stem-replacement-test" type="met:stem-replacement-test"/>
                    <xs:element name="accept" type="met:acceptance-test"/>
                    <xs:element name="reject" type="met:acceptance-test"/>
                    <xs:element name="generation-test" type="met:generation-test"/>
                    <xs:element name="generate" type="met:quick-generation-test"/>
                    <xs:element name="blank" type="xs:string" fixed=""/>
                    <xs:element name="message" type="xs:string"/>
                </xs:choice>
            </xs:choice>    
        </xs:sequence>
        <xs:attribute name="sound-and-fury" type="xs:string"/>
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="show-model" type="met:true-false-type" use="optional" default="true"/>
    </xs:complexType>

    <xs:complexType name="test">
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
        <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
    </xs:complexType>

    <xs:complexType name="transduction-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="interlinear-gloss-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="parsing-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="suggestion-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:stem-label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="recognition-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="should-be-accepted" type="met:yes-no-type"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="acceptance-test">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
                <xs:attribute name="label" type="xs:string" use="optional"/>
                <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
                <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="stem-replacement-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="replacement-stem" type="met:stem"/>
                    <xs:element name="output" type="met:form"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="quick-generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:attribute name="morphemes" type="xs:string"/>
                <xs:attribute name="stem" type="xs:unsignedLong"/>
                <xs:attribute name="lang" type="xs:string"/>
                <xs:attribute name="output" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="morphemes" type="xs:string"/>
                    <xs:element name="stem">
                        <xs:complexType>
                            <xs:attribute name="id" type="xs:unsignedLong" use="required"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:attribute name="filename" type="xs:string"/>
        <xs:attribute name="database-name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem-label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="stem" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem">
        <xs:sequence>
            <xs:element name="form" type="met:form" maxOccurs="unbounded"/>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="form">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="true-false-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yes-no-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== adamb924/mortal-engine/examples/18-Portmanteaux.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Portmanteau Morphemes">
    <morphology-file>18-Portmanteaux.xml</morphology-file>
    <message>Same behavior as 06-Mutually-Exclusive-2.xml</message>
    <accept lang="wk-LA">ata</accept>
    <accept lang="wk-LA">atalar</accept>
    <accept lang="wk-LA">atalary</accept>
    <reject lang="wk-LA">atalarymy</reject>
    <accept lang="wk-LA">göz</accept>
    <accept lang="wk-LA">gözler</accept>
    <accept lang="wk-LA">gözleri</accept>
    <reject lang="wk-LA">gözlarim</reject>
    <reject lang="wk-LA">gözlerym</reject>
    <reject lang="wk-LA">gözlerimi</reject>
    <message>The [Plural][1s-Possessive] can only be parsed with a portmanteau form:</message>
    <accept lang="wk-LA">atalaaaaaam</accept>
    <reject lang="wk-LA">atalarym</reject>
    <accept lang="wk-LA">gözleeeeeem</accept>
    <reject lang="wk-LA">gözlerim</reject>
    <message>The wk-AR writing system is unaffected (these are 'atalarym' and 'gözlerim'):</message>
    <accept lang="wk-AR">آتالارېم</accept>
    <accept lang="wk-AR">گؤزلريم</accept>
    <transduction-test>
        <input lang="wk-AR">آتالارېم</input>
        <output lang="wk-LA">atalaaaaaam</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-AR">گؤزلريم</input>
        <output lang="wk-LA">gözleeeeeem</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-LA">atalaaaaaam</input>
        <output lang="wk-AR">آتالارېم</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-LA">gözleeeeeem</input>
        <output lang="wk-AR">گؤزلريم</output>
    </transduction-test>
</schema>

=== adamb924/mortal-engine/examples/22-Copies-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Copies 2">
    <morphology-file>22-Copies-2.xml</morphology-file>
    <message>Here's how nouns work:</message>
    <accept lang="wk-LA">ataFooPlural</accept>
    <accept lang="wk-LA">ataBar</accept>
    <reject lang="wk-LA">ata</reject>
    <accept lang="wk-LA">ataCaseFooPlural</accept>
    <accept lang="wk-LA">ataCaseBar</accept>
    <reject lang="wk-LA">ataCase</reject>
    <message>With copies, verbs work the same way</message>
    <accept lang="wk-LA">bilFooPlural</accept>
    <accept lang="wk-LA">bilBar</accept>
    <reject lang="wk-LA">bil</reject>
    <accept lang="wk-LA">bilTenseFooPlural</accept>
    <accept lang="wk-LA">bilTenseBar</accept>
    <reject lang="wk-LA">bilTense</reject>
    <message>And with a following suffix</message>
    <accept lang="wk-LA">bilFooPluralMi</accept>
    <accept lang="wk-LA">bilBarMi</accept>
    <reject lang="wk-LA">bilMi</reject>
    <accept lang="wk-LA">bilTenseFooPluralMi</accept>
    <accept lang="wk-LA">bilTenseBarMi</accept>
    <reject lang="wk-LA">bilTenseMi</reject>
</schema>

=== adamb924/mortal-engine/examples/02b-Missing-Form-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Missing Form Example">
        <morphology-file>02b-Missing-Form-2.xml</morphology-file>
        <reject lang="wk-LA">ata</reject>
        <reject lang="wk-AR">آتا</reject>
        <accept lang="wk-LA">atalar</accept>
        <accept lang="wk-LA">atalary</accept>
        <reject lang="wk-LA">atay</reject>
        <reject lang="wk-AR">آتاش</reject>
</schema>

=== adamb924/mortal-engine/examples/00-Minimal.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Minimal Example" >
	<morphology-file>00-Minimal.xml</morphology-file>
	<accept lang="wk-LA">bil</accept>
	<accept lang="wk-LA">ata</accept>
	<message>Any writing system is accepted:</message>
	<accept lang="wk-AR">آی</accept>
	<message>Words not on the list are rejected:</message>
	<reject lang="wk-LA">banana</reject>
</schema>

=== adamb924/mortal-engine/examples/17-Create-Allomorphs-4.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 4">
    <morphology-file>17-Create-Allomorphs-4.xml</morphology-file>
    <message>Consonants don't occur at the end of a word</message>
    <reject lang="wk-LA">sit</reject>
    <reject lang="wk-LA">ben</reject>
    <message>Epenthetic vowels:</message>
    <accept lang="wk-LA">site</accept>
    <accept lang="wk-LA">bene</accept>
    <message>A case suffix:</message>
    <accept lang="wk-LA">sitana</accept>
    <accept lang="wk-LA">benana</accept>
</schema>

=== adamb924/mortal-engine/examples/15-Create-Allomorphs-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 2">
    <morphology-file>15-Create-Allomorphs-2.xml</morphology-file>
    <message>Following non-velars have nOn:</message>
    <accept lang="wk-LA">enonsit</accept>
    <accept lang="wk-LA">enonben</accept>
    <accept lang="wk-LA">enonmot</accept>
    <accept lang="wk-LA">ɛnɔnsɪn</accept>
    <message>Following non-velars cannot have nOŋ:</message>
    <reject lang="wk-LA">enoŋsit</reject>
    <reject lang="wk-LA">enoŋben</reject>
    <reject lang="wk-LA">enoŋmot</reject>
    <reject lang="wk-LA">ɛnɔŋsɪn</reject>
    <message>Following velars show nasal place assimilation</message>
    <accept lang="wk-LA">ɛnɔŋkɛm</accept>
    <accept lang="wk-LA">ɛnɔŋkɔŋ</accept>
    <message>Following velars cannot be preceded by coronals</message>
    <reject lang="wk-LA">ɛnɔnkɛm</reject>
    <reject lang="wk-LA">ɛnɔnkɔŋ</reject>
</schema>
