=== adamb924/mortal-engine/schemata/tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:met="https://www.adambaker.org/mortal-engine/tests"
targetNamespace="https://www.adambaker.org/mortal-engine/tests">

    <xs:element name="tests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sqlite-database" type="met:database" minOccurs="0" maxOccurs="1"/>
                <xs:choice>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="schema" type="met:schema"/>
                    </xs:choice>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
    
    <xs:complexType name="schema" mixed="true">
        <xs:sequence>
            <xs:element name="morphology-file" type="xs:string"/>
            <xs:choice>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="transduction-test" type="met:transduction-test"/>
                    <xs:element name="parsing-test" type="met:parsing-test"/>
                    <xs:element name="recognition-test" type="met:recognition-test"/>
                    <xs:element name="suggestion-test" type="met:suggestion-test"/>
                    <xs:element name="interlinear-gloss-test" type="met:interlinear-gloss-test"/>
                    <xs:element name="stem-replacement-test" type="met:stem-replacement-test"/>
                    <xs:element name="accept" type="met:acceptance-test"/>
                    <xs:element name="reject" type="met:acceptance-test"/>
                    <xs:element name="generation-test" type="met:generation-test"/>
                    <xs:element name="generate" type="met:quick-generation-test"/>
                    <xs:element name="blank" type="xs:string" fixed=""/>
                    <xs:element name="message" type="xs:string"/>
                </xs:choice>
            </xs:choice>    
        </xs:sequence>
        <xs:attribute name="sound-and-fury" type="xs:string"/>
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="show-model" type="met:true-false-type" use="optional" default="true"/>
    </xs:complexType>

    <xs:complexType name="test">
        <xs:attribute name="label" type="xs:string" use="optional"/>
        <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
        <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
    </xs:complexType>

    <xs:complexType name="transduction-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="interlinear-gloss-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>        
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="parsing-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="suggestion-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="output" type="met:stem-label-list" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="recognition-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="should-be-accepted" type="met:yes-no-type"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="acceptance-test">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
                <xs:attribute name="label" type="xs:string" use="optional"/>
                <xs:attribute name="debug" type="met:true-false-type" use="optional"/>
                <xs:attribute name="stem-debug" type="met:true-false-type" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="stem-replacement-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="input" type="met:form"/>
                    <xs:element name="replacement-stem" type="met:stem"/>
                    <xs:element name="output" type="met:form"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="quick-generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:attribute name="morphemes" type="xs:string"/>
                <xs:attribute name="stem" type="xs:unsignedLong"/>
                <xs:attribute name="lang" type="xs:string"/>
                <xs:attribute name="output" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="generation-test">
        <xs:complexContent>
            <xs:extension base="met:test">
                <xs:sequence>
                    <xs:element name="morphemes" type="xs:string"/>
                    <xs:element name="stem">
                        <xs:complexType>
                            <xs:attribute name="id" type="xs:unsignedLong" use="required"/>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="output" type="met:form" minOccurs="1" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:attribute name="filename" type="xs:string"/>
        <xs:attribute name="database-name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem-label-list">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="stem" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stem">
        <xs:sequence>
            <xs:element name="form" type="met:form" maxOccurs="unbounded"/>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="form">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="true-false-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yes-no-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== adamb924/mortal-engine/examples/24-Create-Stem-Allomorphs-2.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Stem Allomorphs 2">
    <morphology-file>24-Create-Stem-Allomorphs-2.xml</morphology-file>
    <message>Identical results as '23-Create-Stem-Allomorphs-1.xml' (but with additons below)</message>
    <accept lang="wk-LA">sit</accept>
    <accept lang="wk-LA">mot</accept>
    <accept lang="wk-LA">sɪn</accept>
    <accept lang="wk-LA">sidu</accept>
    <accept lang="wk-LA">modu</accept>
    <accept lang="wk-LA">sɪnu</accept>
    <reject lang="wk-LA">situ</reject>
    <reject lang="wk-LA">motu</reject>
    <message>Nasal place assimilation</message>
    <accept lang="wk-LA">sɪn</accept>
    <accept lang="wk-LA">sɪŋka</accept>
    <accept lang="wk-LA">kɛm</accept>
    <accept lang="wk-LA">kɛŋka</accept>
    <message>Assimilation is obligatory</message>
    <reject lang="wk-LA">sɪnka</reject>
    <reject lang="wk-LA">kɛmka</reject>
</schema>

=== adamb924/mortal-engine/examples/26-Portmanteau-Stems.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Portmanteau Stems">
    <morphology-file>26-Portmanteau-Stems.xml</morphology-file>
    <accept lang="wk-LA">don</accept>
    <accept lang="wk-LA">dona</accept>
    <accept lang="wk-LA">shunga</accept>
    <reject lang="wk-LA">shua</reject>
    <transduction-test>
        <input lang="wk-AR">دونا</input>
        <output lang="wk-LA">dona</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-LA">dona</input>
        <output lang="wk-AR">دونا</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-AR">شو</input>
        <output lang="wk-LA">shu</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-LA">shu</input>
        <output lang="wk-AR">شو</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-AR">شونگا</input>
        <output lang="wk-LA">shunga</output>
    </transduction-test>
    <transduction-test>
        <input lang="wk-LA">shunga</input>
        <output lang="wk-AR">شونگا</output>
    </transduction-test>
</schema>

=== adamb924/mortal-engine/examples/16-Create-Allomorphs-3.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 3">
    <morphology-file>16-Create-Allomorphs-3.xml</morphology-file>
    <message>Following coronals have nOn:</message>
    <accept lang="wk-LA">enonsit</accept>
    <accept lang="wk-LA">ɛnɔnsɪn</accept>
    <message>Following labials have nOm:</message>
    <accept lang="wk-LA">enomben</accept>
    <accept lang="wk-LA">enommot</accept>
    <message>Following velars have nOŋ</message>
    <accept lang="wk-LA">ɛnɔŋkɛm</accept>
    <accept lang="wk-LA">ɛnɔŋkɔŋ</accept>
    <message>Non-assimilated nasals are not allowed</message>
    <reject lang="wk-LA">enoŋsit</reject>
    <reject lang="wk-LA">enoŋben</reject>
    <reject lang="wk-LA">enoŋmot</reject>
    <reject lang="wk-LA">ɛnɔŋsɪn</reject>
    <reject lang="wk-LA">ɛnɔmkɛm</reject>
    <reject lang="wk-LA">ɛnɔnkɔŋ</reject>
</schema>

=== adamb924/mortal-engine/examples/21-Copies-1.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Copies 1">
    <morphology-file>21-Copies-1.xml</morphology-file>
    <message>Same as 09-Multiple-Models.xml</message>
    <accept lang="wk-LA">bilTense</accept>
    <reject lang="wk-LA">bilCase</reject>
    <reject lang="wk-LA">ataTense</reject>
    <accept lang="wk-LA">ataCase</accept>
    <message>Plurals on nouns</message>
    <accept lang="wk-LA">ataCasePlural</accept>
    <message>Same suffix on verbs</message>
    <accept lang="wk-LA">bilTensePlural</accept>
</schema>

=== adamb924/mortal-engine/examples/all-examples.xml
<?xml version="1.0" encoding="UTF-8"?>
<tests
    xmlns="https://www.adambaker.org/mortal-engine/tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests tests.xsd">
    <schema label="Minimal Example">
        <morphology-file>00-Minimal.xml</morphology-file>
        <recognition-test>
            <input lang="wk-LA">bil</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <message>Any writing system is accepted:</message>
        <recognition-test>
            <input lang="wk-AR">آی</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <message>Words not on the list are rejected:</message>
        <recognition-test>
            <input lang="wk-LA">banana</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Filtering Example">
        <morphology-file>01-Filtered.xml</morphology-file>
        <message>Nouns are accepted, but not verbs:</message>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">bil</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Affix Example">
        <morphology-file>02-Affixes.xml</morphology-file>
        <message>Admittedly, obligatory affixes are kind of silly:</message>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Missing Form Example">
        <morphology-file>02a-Missing-Form.xml</morphology-file>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-AR">آتا</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-AR">آتالار</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Optional Affix Example">
        <morphology-file>03-Optional-Affixes.xml</morphology-file>
        <message>Most affixes are optional:</message>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Tag-Based Allomorphy Example">
        <morphology-file>04-Tag-Allomorphy.xml</morphology-file>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">ataler</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözler</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözlar</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Mutually Exclusive Morphemes Example">
        <morphology-file>05-Mutually-Exclusive.xml</morphology-file>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalary</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalarym</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalarymy</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
    <schema label="Mutually Exclusive Morphemes Example 2">
        <morphology-file>06-Mutually-Exclusive-2.xml</morphology-file>
        <recognition-test>
            <input lang="wk-LA">ata</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalar</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalary</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalarym</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">atalarymy</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">göz</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözler</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözleri</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözlerim</input>
            <should-be-accepted>yes</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözlarim</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözlerym</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
        <recognition-test>
            <input lang="wk-LA">gözlerimi</input>
            <should-be-accepted>no</should-be-accepted>
        </recognition-test>
    </schema>
</tests>

=== adamb924/mortal-engine/examples/12-Phonological-Allomorphy.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Phonological Allomorphy">
    <morphology-file>12-Phonological-Allomorphy.xml</morphology-file>
    <message>Classifiers are obligatory (i.e., no bare stems)</message>
    <reject lang="wk-LA">sɪn</reject>
    <message>Words with ATR vowels get an ATR classifier</message>
    <accept lang="wk-LA">esit</accept>
    <accept lang="wk-LA">eben</accept>
    <accept lang="wk-LA">emot</accept>
    <message>Words with ATR vowels can't take a non-ATR classifier</message>
    <reject lang="wk-LA">ɛsit</reject>
    <reject lang="wk-LA">ɛben</reject>
    <reject lang="wk-LA">ɛmot</reject>
    <message>Non-ATR words take a non-ATR classifier</message>
    <accept lang="wk-LA">ɛsɪn</accept>
    <accept lang="wk-LA">ɛkɛm</accept>
    <accept lang="wk-LA">ɛkɔŋ</accept>
    <message>Non-ATR words cannot take an ATR classifier</message>
    <reject lang="wk-LA">esɪn</reject>
    <reject lang="wk-LA">ekɛm</reject>
    <reject lang="wk-LA">ekɔŋ</reject>
</schema>

=== adamb924/mortal-engine/examples/23-Create-Stem-Allomorphs-1.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Stem Allomorphs 1">
    <morphology-file>23-Create-Stem-Allomorphs-1.xml</morphology-file>
    <message>Unaffixed nouns</message>
    <accept lang="wk-LA">sit</accept>
    <accept lang="wk-LA">mot</accept>
    <accept lang="wk-LA">sɪn</accept>
    <message>Voicing when followed by a vowel-initial suffix</message>
    <accept lang="wk-LA">sidu</accept>
    <accept lang="wk-LA">modu</accept>
    <accept lang="wk-LA">sɪnu</accept>
    <message>Voiceless outputs are ungrammatical in this context</message>
    <reject lang="wk-LA">situ</reject>
    <reject lang="wk-LA">motu</reject>
</schema>

=== adamb924/mortal-engine/examples/25-Create-Allomorphs-7.tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="https://www.adambaker.org/mortal-engine/tests"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://www.adambaker.org/mortal-engine/tests ../schemata/tests.xsd"
	label="Create Allomorphs 7">
    <morphology-file>25-Create-Allomorphs-7.xml</morphology-file>
    <message>nOn assimilates to a following consonant:</message>
    <accept lang="wk-LA">nonsit</accept>
    <accept lang="wk-LA">nomben</accept>
    <accept lang="wk-LA">nommot</accept>
    <accept lang="wk-LA">nonsɪn</accept>
    <message>Following non-velars cannot have nOŋ:</message>
    <reject lang="wk-LA">noŋsit</reject>
    <reject lang="wk-LA">noŋben</reject>
    <reject lang="wk-LA">noŋmot</reject>
    <reject lang="wk-LA">noŋsɪn</reject>
    <message>Following velars show nasal place assimilation</message>
    <accept lang="wk-LA">noŋkɛm</accept>
    <accept lang="wk-LA">noŋkɔŋ</accept>
    <message>Following velars cannot be preceded by coronals</message>
    <reject lang="wk-LA">nonkɛm</reject>
    <reject lang="wk-LA">nonkɔŋ</reject>
    <message>In Arabic, there is assimilation to [n] and [m]</message>
    <accept lang="wk-AR">نونسیت</accept>
    <accept lang="wk-AR">نومبن</accept>
    <accept lang="wk-AR">نومموت</accept>
    <accept lang="wk-AR">نونسین</accept>
    <message>But in Arabic, velar nasal place assimilation does not occur</message>
    <accept lang="wk-AR">نونکم</accept>
    <accept lang="wk-AR">نونکون</accept>
</schema>
